/*
 * Support Service
 * This is a Support service API definition. The API is used for support purpose 
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package digital.vialogic.SupportService.dto;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import digital.vialogic.SupportService.dto.Error;
import digital.vialogic.SupportService.dto.ServiceInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Response model to show when a request shows error
 */
@ApiModel(description = "Response model to show when a request shows error")
@lombok.Builder @lombok.AllArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ErrorResponseData implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_SERVICE_INFO = "serviceInfo";
  @SerializedName(SERIALIZED_NAME_SERVICE_INFO)
  private ServiceInfo serviceInfo;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private Error error;

  public ErrorResponseData() { 
  }

  public ErrorResponseData serviceInfo(ServiceInfo serviceInfo) {
    
    this.serviceInfo = serviceInfo;
    return this;
  }

   /**
   * Get serviceInfo
   * @return serviceInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ServiceInfo getServiceInfo() {
    return serviceInfo;
  }


  public void setServiceInfo(ServiceInfo serviceInfo) {
    this.serviceInfo = serviceInfo;
  }


  public ErrorResponseData error(Error error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Error getError() {
    return error;
  }


  public void setError(Error error) {
    this.error = error;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponseData errorResponseData = (ErrorResponseData) o;
    return Objects.equals(this.serviceInfo, errorResponseData.serviceInfo) &&
        Objects.equals(this.error, errorResponseData.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceInfo, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponseData {\n");
    sb.append("    serviceInfo: ").append(toIndentedString(serviceInfo)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

