/*
 * Support Service
 * This is a Support service API definition. The API is used for support purpose 
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package digital.vialogic.SupportService.dto;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import digital.vialogic.SupportService.dto.PersonDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Person
 */
@lombok.Builder @lombok.AllArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Person implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_PERSON_DETAILS = "personDetails";
  @SerializedName(SERIALIZED_NAME_PERSON_DETAILS)
  private PersonDetails personDetails;

  public Person() { 
  }

  public Person personDetails(PersonDetails personDetails) {
    
    this.personDetails = personDetails;
    return this;
  }

   /**
   * Get personDetails
   * @return personDetails
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PersonDetails getPersonDetails() {
    return personDetails;
  }


  public void setPersonDetails(PersonDetails personDetails) {
    this.personDetails = personDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Person person = (Person) o;
    return Objects.equals(this.personDetails, person.personDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Person {\n");
    sb.append("    personDetails: ").append(toIndentedString(personDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

