/*
 * Support Service
 * This is a Support service API definition. The API is used for support purpose 
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package digital.vialogic.SupportService.dto;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import digital.vialogic.SupportService.dto.ErrorResponseData;
import digital.vialogic.SupportService.dto.SuccessResponseData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Request model for person and service information
 */
@ApiModel(description = "Request model for person and service information")
@lombok.Builder @lombok.AllArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SupportResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_SUCCESS_RESPONSE_DATA = "SuccessResponseData";
  @SerializedName(SERIALIZED_NAME_SUCCESS_RESPONSE_DATA)
  private SuccessResponseData successResponseData;

  public static final String SERIALIZED_NAME_ERROR_RESPONSE_DATA = "ErrorResponseData";
  @SerializedName(SERIALIZED_NAME_ERROR_RESPONSE_DATA)
  private ErrorResponseData errorResponseData;

  public SupportResponse() { 
  }

  public SupportResponse successResponseData(SuccessResponseData successResponseData) {
    
    this.successResponseData = successResponseData;
    return this;
  }

   /**
   * Get successResponseData
   * @return successResponseData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SuccessResponseData getSuccessResponseData() {
    return successResponseData;
  }


  public void setSuccessResponseData(SuccessResponseData successResponseData) {
    this.successResponseData = successResponseData;
  }


  public SupportResponse errorResponseData(ErrorResponseData errorResponseData) {
    
    this.errorResponseData = errorResponseData;
    return this;
  }

   /**
   * Get errorResponseData
   * @return errorResponseData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ErrorResponseData getErrorResponseData() {
    return errorResponseData;
  }


  public void setErrorResponseData(ErrorResponseData errorResponseData) {
    this.errorResponseData = errorResponseData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportResponse supportResponse = (SupportResponse) o;
    return Objects.equals(this.successResponseData, supportResponse.successResponseData) &&
        Objects.equals(this.errorResponseData, supportResponse.errorResponseData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successResponseData, errorResponseData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportResponse {\n");
    sb.append("    successResponseData: ").append(toIndentedString(successResponseData)).append("\n");
    sb.append("    errorResponseData: ").append(toIndentedString(errorResponseData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

